server:
  port: 1234
  error:
    include-message: always

spring:
  datasource:
    password: 123123
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
app:
  jwt:
    secret: java10


